version: '3.8'

services:
  tplink-ddm-exporter:
    image: tplink-ddm-exporter:latest
    container_name: tplink-ddm-exporter
    network_mode: host
    command:
      - -target=192.168.2.96
      - -community=public
      - -addr=:9116
    restart: unless-stopped

